import type { Metadata } from "next";
import { Instrument_Serif, Instrument_Sans } from "next/font/google";
import "../globals.css";
import Container from "@/components/Container";

const InstrumentSerif = Instrument_Serif({
  subsets: ["latin"],
  variable: "--font-heading",
  weight: "400",
});
const InstrumentSans = Instrument_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Container className="py-12 md:py-20 px-6">
      <article className="prose prose-neutral dark:prose-invert prose-headings:font-heading mx-auto w-full prose-headings:font-normal max-w-3xl">
        {children}
      </article>
    </Container>
  );
}
